export enum ReducerActions {
  EXPAND_CATEGORY = "EXPAND_CATEGORY",
  TOGGLE_SETTINGS = "TOGGLE_SETTINGS",
  EXPAND_FILTERS = "EXPAND_FILTERS",
  SHOW_MODAL = "SHOW_MODAL",
  CLOSE_MODAL= "CLOSE_MODAL"
}
